import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { FaCalendarAlt, FaMapMarkerAlt, FaRegClock, FaSearch, FaShieldAlt, FaTicketAlt } from 'react-icons/fa';
import api from '../utils/axios.js';

const features = [[FaRegClock, 'Book in minutes', 'A simple, secure path from discovery to your ticket.'], [FaTicketAlt, 'Plans in one place', 'Keep every event and booking in your personal dashboard.'], [FaShieldAlt, 'Built to feel safe', 'Account verification and protected booking flows by default.']];

export default function Home() {
  const [events, setEvents] = useState([]); const [search, setSearch] = useState(''); const [loading, setLoading] = useState(true);
  useEffect(() => { const controller = new AbortController(); const timer = setTimeout(async () => { try { const { data } = await api.get('/events', { params: { search }, signal: controller.signal }); setEvents(data); } catch (error) { if (error.code !== 'ERR_CANCELED') console.error(error); } finally { setLoading(false); } }, 250); return () => { controller.abort(); clearTimeout(timer); }; }, [search]);
  return <><section className="hero"><div className="hero-content"><span className="eyebrow">The city is calling</span><h1>Find your next <em>unforgettable</em> moment.</h1><p>From creative workshops to electric live shows, discover experiences worth stepping out for.</p><div className="search-box"><FaSearch /><input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Search by event name…" aria-label="Search events" /></div></div></section>
  <section className="feature-grid">{features.map(([Icon, title, text]) => <article className="feature" key={title}><span className="feature-icon"><Icon /></span><h3>{title}</h3><p>{text}</p></article>)}</section>
  <section><div className="section-head"><div><span className="eyebrow">Explore nearby</span><h2>Upcoming events</h2></div><span>{events.length} {events.length === 1 ? 'event' : 'events'} found</span></div>{loading ? <div className="empty">Loading the best events for you…</div> : events.length === 0 ? <div className="empty">No events match that search. Try a different keyword.</div> : <div className="event-grid">{events.map((event) => <article key={event._id} className="event-card"><div className="event-image">{event.image && <img src={event.image} alt={event.title} />}<span className="event-price">{event.ticketPrice ? `₹${event.ticketPrice}` : 'Free'}</span></div><div className="event-body"><span className="event-category">{event.category || 'Event'}</span><h3 className="event-title">{event.title}</h3><div className="event-meta"><span><FaCalendarAlt />{new Date(event.date).toLocaleDateString(undefined, { month: 'short', day: 'numeric', year: 'numeric' })}</span><span><FaMapMarkerAlt />{event.location}</span></div><div className="event-footer"><span>{event.availableSeats} seats remaining</span><Link className="event-link" to={`/events/${event._id}`}>View event →</Link></div></div></article>)}</div>}</section></>;
}
